In [14]:
import pandas as pd
import numpy as np
import ast

In [15]:
df=pd.read_csv("anime.csv")
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [16]:
new_df=df.drop("members",axis="columns")
new_df

,anime_id,name,genre,type,episodes,rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16
...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15
12290,5543,Under World,Hentai,OVA,1,4.28
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46

In [17]:
new_df=new_df.drop("episodes",axis="columns")

In [18]:
new_df=new_df[["anime_id","name","genre","type","rating"]]
new_df

,anime_id,name,genre,type,rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,9.26
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,9.25
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,9.17
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,9.16
...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,4.15
12290,5543,Under World,Hentai,OVA,4.28
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4.88
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,4.98
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,5.46

In [19]:
new_df.iloc[0]

anime_id                                   32281
name                              Kimi no Na wa.
genre       Drama, Romance, School, Supernatural
type                                       Movie
rating                                      9.37
Name: 0, dtype: object

In [20]:
new_df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
rating      230
dtype: int64

In [22]:
new_df.dropna(inplace=True)

In [23]:
new_df.duplicated().sum()

np.int64(0)

In [24]:
new_df.iloc[0].genre

'Drama, Romance, School, Supernatural'

In [25]:
def to_list(val):
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        return [val]  # just wrap it in a list if eval fails

In [27]:
new_df['genre'] = new_df['genre'].apply(to_list)

In [28]:
new_df.head()

,anime_id,name,genre,type,rating
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",Movie,9.37
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",TV,9.26
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",TV,9.25
3,9253,Steins;Gate,"[Sci-Fi, Thriller]",TV,9.17
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",TV,9.16

In [30]:
new_df['type'] = new_df['type'].apply(to_list)
new_df['rating'] = new_df['rating'].apply(to_list)

In [31]:
new_df.head()

,anime_id,name,genre,type,rating
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",[[Movie]],[9.37]
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",[[TV]],[9.26]
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",[[TV]],[9.25]
3,9253,Steins;Gate,"[Sci-Fi, Thriller]",[[TV]],[9.17]
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",[[TV]],[9.16]

In [32]:
new_df["tags"]=new_df["genre"] + new_df["type"] + new_df["rating"]

In [33]:
new_df.head()

,anime_id,name,genre,type,rating,tags
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",[[Movie]],[9.37],"[Drama, Romance, School, Supernatural, [Movie]..."
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",[[TV]],[9.26],"[Action, Adventure, Drama, Fantasy, Magic, Mil..."
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",[[TV]],[9.25],"[Action, Comedy, Historical, Parody, Samurai, ..."
3,9253,Steins;Gate,"[Sci-Fi, Thriller]",[[TV]],[9.17],"[Sci-Fi, Thriller, [TV], 9.17]"
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",[[TV]],[9.16],"[Action, Comedy, Historical, Parody, Samurai, ..."

In [39]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [40]:
new_df['tags'] = new_df['tags'].apply(convert3)

ValueError: malformed node or string: ['Drama, Romance, School, Supernatural', ['Movie'], 9.37]